### PR TITLE
specify bazel version in .bazeliskrc since .bazelversion not working …

### PR DESCRIPTION
**Pull request by tongke6**
…in bzlmod

### CODE REVIEW

**Review by rivertalk — APPROVED** [review]

**Comment by anakinxc** [comment]
This basically forced everyone to use bazelisk.

Is this caused by a bug in Bazel?

**Comment by tongke6** [comment]
> This basically forced everyone to use bazelisk.
> 
> Is this caused by a bug in Bazel?

Bazel don't respect .bazelversion in bzlmod anymore, it only works in workspace mode.

People can use `USE_BAZEL_VERSION=7.4.1 bazel build ...` to specify bazel version if not using bazelisk.

**Comment by Jamie-Cui** [comment]
interesting ...

**Comment by tpppppub** [comment]
> > This basically forced everyone to use bazelisk.
> > Is this caused by a bug in Bazel?
> 
> Bazel don't respect .bazelversion in bzlmod anymore, it only works in workspace mode. [bazelbuild/bazelisk#52](https://github.com/bazelbuild/bazelisk/issues/52)
> 
> People can use `USE_BAZEL_VERSION=7.4.1 bazel build ...` to specify bazel version if not using bazelisk.

Maybe we should document this explicitly [here](https://github.com/secretflow/yacl?tab=readme-ov-file#prerequisites) as there is no .bazelversion file anymore and bazel users do not know the version required.

**Comment by anakinxc** [comment]
well done to bazelisk :D

**Comment by anakinxc** [comment]
@tongke6 Is it possible to just upgrade to [bazel 8](https://github.com/bazelbuild/bazel/releases/tag/8.0.0)?

**Comment by tongke6** [comment]
> @tongke6 Is it possible to just upgrade to [bazel 8](https://github.com/bazelbuild/bazel/releases/tag/8.0.0)?

I will give it a try when all secretflow repos have moved to bzlmod.

**Comment by Jamie-Cui** [comment]
image

**Comment by tongke6** [comment]
@tpppppub add instruction in this PR: https://github.com/secretflow/yacl/pull/444

**Pull request merged**
